import {
  AccountBookOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  CommentOutlined,
  CompassOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  DollarOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  GlobalOutlined,
  IdcardOutlined,
  MoonOutlined,
  ProfileOutlined,
  ReconciliationOutlined,
  RollbackOutlined,
  SettingOutlined,
  ShopOutlined,
  SolutionOutlined,
  StarOutlined,
  SwapOutlined,
  TeamOutlined,
  UserOutlined,
  WalletOutlined,
} from "@ant-design/icons";
import type { ReactNode } from "react";
import type { NavIcon } from "@/lib/nav";

export const NAV_ICONS: Record<NavIcon, ReactNode> = {
  dashboard: <DashboardOutlined />,
  ticket: <GlobalOutlined />,
  file: <FileTextOutlined />,
  swap: <SwapOutlined />,
  visa: <IdcardOutlined />,
  tour: <CompassOutlined />,
  hajj: <MoonOutlined />,
  team: <TeamOutlined />,
  umrah: <StarOutlined />,
  refund: <RollbackOutlined />,
  receipt: <FileDoneOutlined />,
  bank: <BankOutlined />,
  cheque: <CreditCardOutlined />,
  payroll: <SolutionOutlined />,
  expense: <WalletOutlined />,
  loan: <DollarOutlined />,
  client: <UserOutlined />,
  vendor: <ShopOutlined />,
  agent: <ReconciliationOutlined />,
  quote: <ProfileOutlined />,
  passport: <AuditOutlined />,
  report: <BarChartOutlined />,
  settings: <SettingOutlined />,
  feedback: <CommentOutlined />,
};

export const FALLBACK_ICON = <AccountBookOutlined />;
