// Starter reference data copied into every new agency. Agencies can edit or
// deactivate any of it afterwards.

export const AIRPORTS: [iata: string, name: string, city: string, country: string][] = [
  ["DAC", "Hazrat Shahjalal International Airport", "Dhaka", "Bangladesh"],
  ["CGP", "Shah Amanat International Airport", "Chattogram", "Bangladesh"],
  ["ZYL", "Osmani International Airport", "Sylhet", "Bangladesh"],
  ["CXB", "Cox's Bazar Airport", "Cox's Bazar", "Bangladesh"],
  ["JSR", "Jashore Airport", "Jashore", "Bangladesh"],
  ["RJH", "Shah Makhdum Airport", "Rajshahi", "Bangladesh"],
  ["SPD", "Saidpur Airport", "Saidpur", "Bangladesh"],
  ["BZL", "Barishal Airport", "Barishal", "Bangladesh"],
  ["JED", "King Abdulaziz International Airport", "Jeddah", "Saudi Arabia"],
  ["MED", "Prince Mohammad bin Abdulaziz Airport", "Madinah", "Saudi Arabia"],
  ["RUH", "King Khalid International Airport", "Riyadh", "Saudi Arabia"],
  ["DMM", "King Fahd International Airport", "Dammam", "Saudi Arabia"],
  ["DXB", "Dubai International Airport", "Dubai", "United Arab Emirates"],
  ["AUH", "Abu Dhabi International Airport", "Abu Dhabi", "United Arab Emirates"],
  ["SHJ", "Sharjah International Airport", "Sharjah", "United Arab Emirates"],
  ["DOH", "Hamad International Airport", "Doha", "Qatar"],
  ["MCT", "Muscat International Airport", "Muscat", "Oman"],
  ["KWI", "Kuwait International Airport", "Kuwait City", "Kuwait"],
  ["BAH", "Bahrain International Airport", "Manama", "Bahrain"],
  ["KUL", "Kuala Lumpur International Airport", "Kuala Lumpur", "Malaysia"],
  ["SIN", "Singapore Changi Airport", "Singapore", "Singapore"],
  ["BKK", "Suvarnabhumi Airport", "Bangkok", "Thailand"],
  ["CGK", "Soekarno-Hatta International Airport", "Jakarta", "Indonesia"],
  ["CCU", "Netaji Subhas Chandra Bose International Airport", "Kolkata", "India"],
  ["DEL", "Indira Gandhi International Airport", "Delhi", "India"],
  ["BOM", "Chhatrapati Shivaji Maharaj International Airport", "Mumbai", "India"],
  ["MAA", "Chennai International Airport", "Chennai", "India"],
  ["KTM", "Tribhuvan International Airport", "Kathmandu", "Nepal"],
  ["CMB", "Bandaranaike International Airport", "Colombo", "Sri Lanka"],
  ["MLE", "Velana International Airport", "Male", "Maldives"],
  ["IST", "Istanbul Airport", "Istanbul", "Turkey"],
  ["CAN", "Guangzhou Baiyun International Airport", "Guangzhou", "China"],
  ["HKG", "Hong Kong International Airport", "Hong Kong", "China"],
  ["NRT", "Narita International Airport", "Tokyo", "Japan"],
  ["ICN", "Incheon International Airport", "Seoul", "South Korea"],
  ["LHR", "Heathrow Airport", "London", "United Kingdom"],
  ["MAN", "Manchester Airport", "Manchester", "United Kingdom"],
  ["JFK", "John F. Kennedy International Airport", "New York", "United States"],
  ["YYZ", "Toronto Pearson International Airport", "Toronto", "Canada"],
  ["SYD", "Sydney Airport", "Sydney", "Australia"],
];

export const AIRLINES: [iata: string, name: string][] = [
  ["BG", "Biman Bangladesh Airlines"],
  ["BS", "US-Bangla Airlines"],
  ["2A", "Air Astra"],
  ["VQ", "Novoair"],
  ["EK", "Emirates"],
  ["QR", "Qatar Airways"],
  ["EY", "Etihad Airways"],
  ["SV", "Saudia"],
  ["XY", "flynas"],
  ["FZ", "flydubai"],
  ["G9", "Air Arabia"],
  ["WY", "Oman Air"],
  ["GF", "Gulf Air"],
  ["KU", "Kuwait Airways"],
  ["J9", "Jazeera Airways"],
  ["TK", "Turkish Airlines"],
  ["SQ", "Singapore Airlines"],
  ["MH", "Malaysia Airlines"],
  ["OD", "Batik Air Malaysia"],
  ["AK", "AirAsia"],
  ["TG", "Thai Airways"],
  ["AI", "Air India"],
  ["6E", "IndiGo"],
  ["UL", "SriLankan Airlines"],
  ["CZ", "China Southern Airlines"],
  ["MU", "China Eastern Airlines"],
  ["CX", "Cathay Pacific"],
  ["BA", "British Airways"],
];

export const COUNTRIES: [name: string, iso2: string][] = [
  ["Bangladesh", "BD"],
  ["Saudi Arabia", "SA"],
  ["United Arab Emirates", "AE"],
  ["Qatar", "QA"],
  ["Oman", "OM"],
  ["Kuwait", "KW"],
  ["Bahrain", "BH"],
  ["Malaysia", "MY"],
  ["Singapore", "SG"],
  ["Thailand", "TH"],
  ["Indonesia", "ID"],
  ["India", "IN"],
  ["Nepal", "NP"],
  ["Bhutan", "BT"],
  ["Sri Lanka", "LK"],
  ["Maldives", "MV"],
  ["Turkey", "TR"],
  ["China", "CN"],
  ["Japan", "JP"],
  ["South Korea", "KR"],
  ["United Kingdom", "GB"],
  ["United States", "US"],
  ["Canada", "CA"],
  ["Australia", "AU"],
  ["Italy", "IT"],
  ["Germany", "DE"],
  ["France", "FR"],
];

export const PRODUCTS: [
  name: string,
  type: "AIR" | "VISA" | "TOUR" | "HAJJ" | "UMRAH" | "HOTEL" | "INSURANCE" | "OTHER",
][] = [
  ["Air Ticket", "AIR"],
  ["Visa Processing", "VISA"],
  ["Tour Package", "TOUR"],
  ["Hajj Package", "HAJJ"],
  ["Umrah Package", "UMRAH"],
  ["Hotel Booking", "HOTEL"],
  ["Travel Insurance", "INSURANCE"],
  ["Other Service", "OTHER"],
];

export const VISA_TYPES = [
  "Tourist",
  "Business",
  "Work",
  "Student",
  "Medical",
  "Umrah",
  "Family Visit",
  "Transit",
];
export const ROOM_TYPES = ["Single", "Double", "Twin", "Triple", "Quad", "Suite"];
export const TRANSPORT_TYPES = ["Car", "Microbus", "Bus", "Train", "Launch", "Flight"];
export const PASSPORT_STATUSES = [
  "Received from Client",
  "Submitted to Embassy",
  "Visa Approved",
  "Visa Rejected",
  "Delivered to Client",
];
export const MAHARAM_RELATIONS = [
  "Husband",
  "Father",
  "Son",
  "Brother",
  "Grandson",
  "Father-in-law",
  "Son-in-law",
  "Nephew",
  "Uncle",
];
export const DEPARTMENTS = ["Management", "Ticketing", "Visa", "Hajj & Umrah", "Accounts", "Sales"];
export const DESIGNATIONS = [
  "Managing Director",
  "Manager",
  "Ticketing Officer",
  "Visa Officer",
  "Accountant",
  "Sales Executive",
];
export const CLIENT_CATEGORIES: [name: string, prefix: string][] = [
  ["Individual", "IND"],
  ["Corporate", "CORP"],
  ["B2B Agency", "B2B"],
];
